#!/usr/bin/env python

from lib.parser import parser
from lib.apps import timer, alarm

def main():
    args = parser()

    if args.app == 'timer':
        if args.sec != None:
            timer.init(args.sec, args.msg)

    if args.app == 'alarm':
        if args.time != None:
            alarm.init(args.time, args.msg)

if __name__ == "__main__":
    main()
